name: Build and Publish Image

on:
  push:
    branches:
      - main
      
jobs:
    build-and-publish:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@v3
          
        - name: 'Login via Azure CLI'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}
        
        - name: 'Build and push image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
            
        - name: 'Build and Push Container Image to registry' 
          run: az acr build --registry CsdContainerDemoRegistry --image WebApiImage /ContainerizedAppDeploymentDemo/Dockerfile
         
